# Generated by Django 4.1.5 on 2023-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('sal', models.FloatField()),
            ],
        ),
    ]
